logging:
  level:
    root: info
    # update logging level for JDBC
    org:
      springframework:
        jdbc:
          core: trace
  file:
    name: dmshed.log
    path: /

spring:
  mvc:
    format:
      date: iso #defaulf format date
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        # create or update or validate ddl
        hbm2ddl:
          auto: validate
        jdbc:
          #for update, delete
          batch_size: 50
          #for select
          fetch_size: 50
    # to disable transactions at the controller level by default
    open-in-view: false
#oauth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: pass
            client-secret: pass
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email




